# Generated by Django 3.0.5 on 2020-05-14 14:51
import shutil
import os
from django.db import migrations
from django.core.files import File
from django.conf import settings

FIXTURE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "fixtures")


def forward(apps, schema_editor):
    Sound = apps.get_model("alarms", "Sound")
    src = os.path.join(FIXTURE_DIR, "Annoying_Alarm_Clock.mp3")
    dst = os.path.join(settings.MEDIA_ROOT, "Annoying_Alarm_Clock.mp3")
    shutil.copyfile(src, dst)
    with open(dst, "rb") as fh:
        wrapped_file = File(fh)
        Sound.objects.create(
            id=1, name="buzzer", audio=wrapped_file,
        )


def backward(apps, schema_editor):
    Sound = apps.get_model("alarms", "Sound")
    Sound.objects.get(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward, backward)]
